### PR TITLE
Put Initial Spawn Behind A Flag

### PR DESCRIPTION
**Pull request by dancork**
I forked this a while ago and have been using the fork in my projects. Thought I'd open this PR to see what you guys thought.

It prevents the initial spawn from occurring unless we pass a flag `-S` or `--init-spawn`.

### CODE REVIEW

**Comment by caseywebdev** [comment]
The default would definitely need to be spawning initially. Out of curiosity what's your use case for not spawning initially?

**Comment by dancork** [comment]
I've mostly been using it with an SSG. I use it to watch a set of files for changes and run a small part of the initial build step, not the entire thing.

Happy to change the default. Any idea how that is done with commander?

**Comment by caseywebdev** [comment]
You would need to change the long version of the flag to `--no-init-spawn` and I believe commander will invert the value automatically. See `--no-color`, for example.

**Comment by dancork** [comment]
@caseywebdev ah, that's cool. have updated it.

**Comment by caseywebdev** [comment]
LGTM, would you mind squashing these commits since they all equate to one logical change?

**Comment by dancork** [comment]
Consider them squished

**Comment by caseywebdev** [comment]
:fireworks:

**Comment by caseywebdev** [comment]
Released in `0.6.6`

**Pull request merged**
